import Testing
import Foundation

struct ConfigAutoSetRunnerTests {

    // MARK: - Helpers

    private func makeTempDir() throws -> URL {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("tian-auto-set-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }

    private func cleanup(_ dir: URL) {
        try? FileManager.default.removeItem(at: dir)
    }

    /// Initializes a bare git repo at the given directory.
    private func gitInit(at dir: URL) throws {
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        p.arguments = ["git", "init", "-q"]
        p.currentDirectoryURL = dir
        try p.run()
        p.waitUntilExit()
        precondition(p.terminationStatus == 0, "git init failed")
    }

    // MARK: - resolveRepoRoot

    @Test func resolveRepoRoot_returnsRepoRoot_whenCwdIsInsideRepo() throws {
        let tmp = try makeTempDir()
        defer { cleanup(tmp) }
        try gitInit(at: tmp)

        let sub = tmp.appendingPathComponent("a/b/c")
        try FileManager.default.createDirectory(at: sub, withIntermediateDirectories: true)

        let runner = ConfigAutoSetRunner(invoker: StubClaudeInvoker(output: ""))
        let resolved = try runner.resolveRepoRoot(from: sub)

        // resolvingSymlinksInPath() normalizes /var/ vs /private/var/ on macOS.
        #expect(resolved.resolvingSymlinksInPath() == tmp.resolvingSymlinksInPath())
    }

    @Test func resolveRepoRoot_throws_whenCwdIsNotInsideRepo() throws {
        let tmp = try makeTempDir()
        defer { cleanup(tmp) }
        // No `git init` — tmp is not a repo.

        let runner = ConfigAutoSetRunner(invoker: StubClaudeInvoker(output: ""))
        #expect(throws: CLIError.self) {
            try runner.resolveRepoRoot(from: tmp)
        }
    }

    // MARK: - run() happy path

    @Test func run_writesConfigFile_fromValidTOML() throws {
        let tmp = try makeTempDir()
        defer { cleanup(tmp) }
        try gitInit(at: tmp)

        let toml = """
        # tian worktree config — auto-generated by `tian config auto-set`
        [[setup]]
        command = "bun install"

        [[copy]]
        source = ".env.local"
        dest = "."
        """
        let stub = StubClaudeInvoker(output: toml)
        let runner = ConfigAutoSetRunner(invoker: stub)

        let result = try runner.run(cwd: tmp, force: false, model: "sonnet")

        #expect(result.setupCount == 1)
        #expect(result.copyCount == 1)

        // File written at <repo>/.tian/config.toml.
        let configURL = tmp.appendingPathComponent(".tian/config.toml")
        #expect(FileManager.default.fileExists(atPath: configURL.path))
        let written = try String(contentsOf: configURL, encoding: .utf8)
        #expect(written == toml)

        // Invoker received the cwd and model.
        #expect(stub.calls.count == 1)
        #expect(stub.calls[0].cwd.resolvingSymlinksInPath() == tmp.resolvingSymlinksInPath())
        #expect(stub.calls[0].model == "sonnet")
    }

    @Test func run_createsDotTianDirectory_ifMissing() throws {
        let tmp = try makeTempDir()
        defer { cleanup(tmp) }
        try gitInit(at: tmp)
        // No .tian/ dir yet.

        let stub = StubClaudeInvoker(output: "")
        let runner = ConfigAutoSetRunner(invoker: stub)

        _ = try runner.run(cwd: tmp, force: false, model: "sonnet")

        var isDir: ObjCBool = false
        let dotTian = tmp.appendingPathComponent(".tian").path
        #expect(FileManager.default.fileExists(atPath: dotTian, isDirectory: &isDir))
        #expect(isDir.boolValue)
    }
}

// MARK: - StubClaudeInvoker

/// Test double that returns pre-configured output and records calls.
final class StubClaudeInvoker: ClaudeInvoker {
    var output: String
    var error: Error?
    private(set) var calls: [(prompt: String, cwd: URL, model: String)] = []

    init(output: String = "", error: Error? = nil) {
        self.output = output
        self.error = error
    }

    func run(prompt: String, cwd: URL, model: String) throws -> String {
        calls.append((prompt: prompt, cwd: cwd, model: model))
        if let error { throw error }
        return output
    }
}
