import Foundation

/// Prompt template for `tian config auto-set`.
///
/// Held as a single static constant so it is diffable, reviewable, and
/// unit-testable without invoking `claude -p`.
enum AutoSetPrompt {
    static let template: String = """
    Analyze this repository and generate a `.tian/config.toml` file.

    Output ONLY valid TOML — no markdown fences, no explanation, no prose.
    Do not wrap the output in triple backticks.

    # Schema

    Only these two sections are in scope. Omit everything else.

    ```
    # [[setup]] — one-shot shell commands run once when a worktree is
    # created for this repo. Each [[setup]] is an independent entry with
    # a required `command` field. Commands run sequentially with the
    # worktree root as cwd.
    [[setup]]
    command = "<shell command>"

    # [[copy]] — files copied from the main worktree into each new worktree.
    # `source` is a glob relative to repo root; `dest` is a path relative
    # to repo root. A trailing `/` on dest means "place files inside this
    # directory".
    [[copy]]
    source = "<glob>"
    dest = "<path>"
    ```

    # Guidelines

    - Include `[[setup]]` for: dependency install (`bun install`,
      `npm ci`, `cargo fetch`, `uv sync`, `bundle install`), copying
      example env files (`cp .env.example .env`), and project-specific
      bootstrap scripts found in `scripts/`, `Makefile`, or
      `package.json`'s `scripts.setup`.
    - Include `[[copy]]` for: `.env*` files (but NOT `.env.example`,
      which git already tracks), `*.local.*` files, and local-only
      secrets the `.gitignore` lists that would break dev if missing.
    - If nothing obvious is detected, emit a short header comment
      saying so and leave both arrays empty.
    - Omit `worktree_dir`, `setup_timeout`, `shell_ready_delay`, and
      `[layout]` — they are intentionally out of scope for this command.

    # Examples

    ## Example 1: Node/Bun repo

    Given a repo with `package.json` containing `"packageManager": "bun@1"`,
    a `.env.example` tracked in git, and a `.env.local` in `.gitignore`,
    output:

    # tian worktree config — auto-generated by `tian config auto-set`
    [[setup]]
    command = "bun install"

    [[setup]]
    command = "cp .env.example .env"

    [[copy]]
    source = ".env.local"
    dest = "."

    ## Example 2: Swift / XcodeGen repo

    Given a repo with `project.yml`, `scripts/build-ghostty.sh`, and a
    `.ghostty-src` symlink in `.gitignore`, output:

    # tian worktree config — auto-generated by `tian config auto-set`
    [[setup]]
    command = "xcodegen generate"

    [[setup]]
    command = "MAIN=$(dirname \\"$(git rev-parse --path-format=absolute --git-common-dir)\\") && ln -sfn \\"$MAIN/.ghostty-src\\" .ghostty-src"

    Now analyze the current repository (your `cwd` is the repo root) and
    produce the TOML.
    """
}
